version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/packages/eslint-config'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 99
    target-branch: 'dev'
    versioning-strategy: 'increase'
