name: 'Release'

on:
  push:
    tags:
      - 'eslint-config@*'

jobs:
  release:
    runs-on: 'ubuntu-latest'

    - name: 'Grab Version'
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    steps:
      - name: 'Publish Release'
        uses: 'actions/github-script@v6'
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.VERSION,
              name: process.env.VERSION,
              draft: false,
              prerelease: false
            })
